[2024-05-06T19:05:44.041+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T19:05:44.082+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_validation_dag_v2.fetch_data scheduled__2024-05-06T18:01:00+00:00 [queued]>
[2024-05-06T19:05:44.090+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_validation_dag_v2.fetch_data scheduled__2024-05-06T18:01:00+00:00 [queued]>
[2024-05-06T19:05:44.175+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2024-05-06T19:05:45.115+0000] {taskinstance.py:2327} INFO - Executing <Task(_PythonDecoratedOperator): fetch_data> on 2024-05-06 18:01:00+00:00
[2024-05-06T19:05:45.123+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_validation_dag_v2', 'fetch_data', 'scheduled__2024-05-06T18:01:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/***-dags/datalake/data_validation_dag.py', '--cfg-path', '/tmp/tmpz_su3hwv']
[2024-05-06T19:05:45.125+0000] {standard_task_runner.py:91} INFO - Job 199: Subtask fetch_data
[2024-05-06T19:05:45.126+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-06T19:05:45.127+0000] {standard_task_runner.py:63} INFO - Started process 185 to run task
[2024-05-06T19:05:45.846+0000] {task_command.py:426} INFO - Running <TaskInstance: data_validation_dag_v2.fetch_data scheduled__2024-05-06T18:01:00+00:00 [running]> on host da062ce1c016
[2024-05-06T19:05:48.236+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='data_validation_dag_v2' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T18:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T18:01:00+00:00'
[2024-05-06T19:05:48.237+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T19:05:50.472+0000] {python.py:237} INFO - Done. Returned value was:             date_of_interest case_count  ... si_death_count_7day_avg incomplete
0    2020-02-29T00:00:00.000          1  ...                       0          0
1    2020-03-01T00:00:00.000          0  ...                       0          0
2    2020-03-02T00:00:00.000          0  ...                       0          0
3    2020-03-03T00:00:00.000          1  ...                       0          0
4    2020-03-04T00:00:00.000          5  ...                       0          0
..                       ...        ...  ...                     ...        ...
995  2022-11-20T00:00:00.000       1339  ...                       1          0
996  2022-11-21T00:00:00.000       3010  ...                       1          0
997  2022-11-22T00:00:00.000       2701  ...                       1          0
998  2022-11-23T00:00:00.000       2701  ...                       1          0
999  2022-11-24T00:00:00.000       1007  ...                       1          0

[1000 rows x 55 columns]
[2024-05-06T19:05:50.676+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T19:05:51.112+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=data_validation_dag_v2, task_id=fetch_data, execution_date=20240506T180100, start_date=20240506T190544, end_date=20240506T190551
[2024-05-06T19:05:51.618+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-06T19:05:51.802+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-06T19:05:51.857+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
